import { BlogPost } from '@/lib/blogs';

export const blogPosts: BlogPost[] = [
  {
    slug: "beyaz-blackout-pergola",
    title: "Beyaz Blackout Pergola Kumaşı Neden Sararır?",
    metaTitle: "Beyaz Blackout Pergola Kumaşı Sararması",
    metaDescription: "Beyaz blackout pergola kumaşı sararması is, duman, polen kaynaklıdır. pH 6.8 nötr temizlik ile ilk gün parlaklığına döner.",
    category: "Pergola",
    date: "18 Mayıs 2026",
    author: "PergoClean",
    image: "/assets/Blog/Blog_Pergola_2_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.jpg",
    excerpt: "Beyaz blackout pergola kumaşlarının sararma nedenleri ve profesyonel temizlik yöntemleri.",
    keywords: ["pergola temizliği", "blackout kumaş"],
    districts: ["Çankaya"],
    content: "<h2>Beyaz Pergola Temizliği</h2><p>Doğru bakım ile pergola kumaşınızın ömrünü uzatın.</p>",
    snippet: "Profesyonel bakım ile pergola kumaşları ilk günkü gibi beyaz kalır.",
    faqs: [{ q: "Neden sararır?", a: "Toz ve UV etkisinden." }]
  },
  {
    slug: "pergola-temizligi-vs-bakimi",
    title: "Pergola Temizliği ile Pergola Bakımı Arasındaki Teknik Fark",
    metaTitle: "Pergola Temizliği ve Bakımı Farkı",
    metaDescription: "Temizlik yüzeyi güzelleştirir, bakım sistemi bütünüyle kalibre eder.",
    category: "Bakım",
    date: "18 Mayıs 2026",
    author: "PergoClean",
    image: "/assets/Blog/Blog_BioClimatic_2_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.jpg",
    excerpt: "Pergola temizliği ile bakımı arasındaki farkı keşfedin.",
    keywords: ["pergola temizliği", "bakım"],
    districts: ["Etimesgut"],
    content: "<h2>Teknik Bakım</h2><p>Temizlik ve bakım ayrı ayrı yapılmalıdır.</p>",
    snippet: "Bakım, sistem ömrünü %40 uzatır.",
    faqs: [{ q: "Fark nedir?", a: "Bakım kalibrasyon gerektirir." }]
  },
  {
    slug: "bioclimatic-aluminyum-tavan",
    title: "BioClimatic Alüminyum Tavan Bakımı",
    metaTitle: "BioClimatic Alüminyum Tavan",
    metaDescription: "BioClimatic sistemler için teknik bakım protokolleri.",
    category: "BioClimatic",
    date: "18 Mayıs 2026",
    author: "PergoClean",
    image: "/assets/Blog/Blog_BioClimatic_3_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.jpg",
    excerpt: "BioClimatic alüminyum tavan sistemleri için bakım ipuçları.",
    keywords: ["bioclimatic", "alüminyum tavan"],
    districts: ["Söğütözü"],
    content: "<h2>BioClimatic Bakım</h2><p>Motor ve drenaj kontrolü hayatidir.</p>",
    snippet: "Sessiz ve sorunsuz çalışması için bakım şarttır.",
    faqs: [{ q: "Ne zaman yapılır?", a: "Sezonda bir." }]
  },
  {
    slug: "zip-perde-wintent",
    title: "Zip Perde ve Wintent Bakımı",
    metaTitle: "Zip Perde ve Wintent",
    metaDescription: "Zip perde ve Wintent sistemler için bakım kalibrasyonu.",
    category: "Zip Perde",
    date: "18 Mayıs 2026",
    author: "PergoClean",
    image: "/assets/Blog/Blog_ZipScreen_ZipPerde_2_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.jpg",
    excerpt: "Zip perde sistemlerinin uzun ömürlü olması için bakım şart.",
    keywords: ["zip perde", "wintent"],
    districts: ["Muratpaşa"],
    content: "<h2>Zip Perde Bakım</h2><p>Menteşe yağlama önemlidir.</p>",
    snippet: "Zip perde sistemlerini ilk günkü gerginliğinde tutun.",
    faqs: [{ q: "Nasıl bakım yapılır?", a: "Ray temizliği ile." }]
  },
  {
    slug: "rolling-roof-cam-tavan",
    title: "Rolling Roof ve Cam Tavan Restorasyonu",
    metaTitle: "Rolling Roof ve Cam Tavan",
    metaDescription: "Leke giderme ve yalıtım kontrolü.",
    category: "Rolling Roof",
    date: "18 Mayıs 2026",
    author: "PergoClean",
    image: "/assets/Blog/Blog_BioClimatic_RollingRoof_1_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.jpg",
    excerpt: "Rolling Roof sistemlerde leke ve yalıtım bakımı.",
    keywords: ["rolling roof", "cam tavan"],
    districts: ["Yenimahalle"],
    content: "<h2>Restorasyon</h2><p>Hydrophobic kaplama ile camları koruyun.</p>",
    snippet: "Camlarınızı şeffaf ve lekesiz tutun.",
    faqs: [{ q: "Sızıntı olur mu?", a: "Bakım ile engellenir." }]
  },
  {
    slug: "gunes-paneli-kepenk",
    title: "Güneş Paneli ve Kepenk Bakımı",
    metaTitle: "Güneş Paneli ve Kepenk",
    metaDescription: "Verimlilik ve güvenlik bakımı.",
    category: "Diğer",
    date: "18 Mayıs 2026",
    author: "PergoClean",
    image: "/assets/Blog/Blog_GunesPaneli_2_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.jpg",
    excerpt: "Güneş paneli ve kepenk sistemlerinin verimli çalışması için bakım.",
    keywords: ["güneş paneli", "kepenk"],
    districts: ["Çankaya"],
    content: "<h2>Enerji Verimi</h2><p>Panel temizliği ile verimi artırın.</p>",
    snippet: "Bakım, enerji üretiminizi maksimumda tutar.",
    faqs: [{ q: "Kepenk neden tutukluk yapar?", a: "Toz birikimi yüzünden." }]
  },
  {
    slug: "iklim-yuzey-hasari",
    title: "İklim Kaynaklı Yüzey Hasarları",
    metaTitle: "İklim ve Yüzey Hasarı",
    metaDescription: "Toz ve tuz kaynaklı hasarlardan korunma.",
    category: "Bakım",
    date: "18 Mayıs 2026",
    author: "PergoClean",
    image: "/assets/Blog/Blog_BioClimatic_RollingRoof_2_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.jpg",
    excerpt: "Ankara ve Antalya ikliminin sistemlere etkisi.",
    keywords: ["iklim", "yüzey hasarı"],
    districts: ["Konyaaltı"],
    content: "<h2>İklim Analizi</h2><p>Tuz ve toz korozyona yol açar.</p>",
    snippet: "İklim uyumlu bakım ile sistem ömrünü uzatın.",
    faqs: [{ q: "Hasar önlenebilir mi?", a: "Periyodik bakım şart." }]
  },
  {
    slug: "zincir-isletme-standarti",
    title: "Zincir İşletmelerde Bakım",
    metaTitle: "Zincir İşletme Bakımı",
    metaDescription: "Marka standartlarında periyodik bakım.",
    category: "Kurumsal",
    date: "18 Mayıs 2026",
    author: "PergoClean",
    image: "/assets/Blog/Blog_ZipScreen_ZipPerde_3_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.jpg",
    excerpt: "Zincir işletmeler için standartlaştırılmış bakım protokolü.",
    keywords: ["zincir işletme", "kurumsal"],
    districts: ["Genel"],
    content: "<h2>Kurumsal Bakım</h2><p>Tüm şubelerde standart hizmet.</p>",
    snippet: "Marka imajınız için düzenli bakım.",
    faqs: [{ q: "Neden önemlidir?", a: "Müşteri sadakati için." }]
  },
  {
    slug: "teknik-bakim-muhendisligi",
    title: "Teknik Bakım Mühendisliği",
    metaTitle: "Teknik Bakım Mühendisliği",
    metaDescription: "Neden teknik bakım temizlikten üstündür?",
    category: "Mühendislik",
    date: "18 Mayıs 2026",
    author: "PergoClean",
    image: "/assets/Blog/Blog_BioClimatic_RollingRoof_3_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.jpg",
    excerpt: "Profesyonel teknik bakım ile sistemlerinizi koruyun.",
    keywords: ["teknik bakım", "mühendislik"],
    districts: ["Genel"],
    content: "<h2>Mühendislik Yaklaşımı</h2><p>Kontrollü basınç ve pH ile temizlik.</p>",
    snippet: "Teknik bakım, sistemin ömrünü garantiye alır.",
    faqs: [{ q: "Fark nedir?", a: "Sistem bütünlüğü." }]
  },
  {
    slug: "insaat-sonrasi-restorasyon",
    title: "İnşaat Sonrası Restorasyon",
    metaTitle: "İnşaat Sonrası Restorasyon",
    metaDescription: "İnşaat sonrası sistemleriniz için özel temizlik.",
    category: "Bakım",
    date: "18 Mayıs 2026",
    author: "PergoClean",
    image: "/assets/Blog/Blog_ZipScreen_ZipPerde_7_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.jpg",
    excerpt: "Yeni biten projeleriniz için özel temizlik çözümleri.",
    keywords: ["inşaat", "restorasyon"],
    districts: ["Muratpaşa"],
    content: "<h2>Tadilat Sonrası</h2><p>İnşaat tozlarından arındırın.</p>",
    snippet: "İlk kullanımda temizlik garantisi.",
    faqs: [{ q: "Ne zaman yapılmalı?", a: "Hemen tadilat sonrası." }]
  }
];
