export interface BlogPost {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  category: string;
  date: string;
  author: string;
  image: string;
  excerpt: string;
  keywords: string[];
  districts: string[];
  content: string;
  snippet: string;
  faqs: { q: string; a: string }[];
}

export const blogs: BlogPost[] = [
  { slug: "ankara-cankaya-bioclimatic-bakimi", title: "Ankara Çankaya’da BioClimatic Pergola Bakımı: İlk Gün Performansı", metaTitle: "Çankaya BioClimatic Bakım", metaDescription: "BioClimatic alüminyum tavan sistemleri Ankara Çankaya’da pH nötr kimyasallar ve HEPA toz alma ile ilk gün görünümüne kavuşur.", category: "BioClimatic", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_BioClimatic_2_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "BioClimatic sistemlerin ömrü, alüminyum profillerin nötr pH temizliği ve motor dişlilerinin düzenli yağlanmasıyla %40 uzar.", keywords: ["BioClimatic", "Çankaya", "Bakım"], districts: ["Çankaya"], content: "<h2>Teknik Protokol</h2><p>HEPA 99.97% @ 0.3µm ile toz alma, 2 bar buhar ve Avrupa OEM onaylı kimyasallar kullanıyoruz. BioClimatic pergolalar, hareketli lamelleri ve entegre drenaj yapısıyla açık alan konforunu yeniden tanımlar. Ancak Ankara’nın tozlu iklimi, polen yükü ve egzoz partikülleri, sistem toleranslarını hızla bozar. PergoClean olarak klasik temizlik mantığı yerine, teknik bakım mühendisliği uyguluyoruz.</p><h3>Uygulama</h3><p>Ardından 120–130°C, 2.5 bar yüzey uyumlu sıcak buhar ile alüminyum anotlama tabakası zarar görmeden yumuşatılır. Sadece Avrupa OEM onaylı pH 6.8–7.2 nötr ajanlar kullanılarak, kireç ve karbon tabakası güvenli şekilde çözülür. Limit switch kalibrasyonu ve ±0.5mm ray hizalama toleransları ile otomasyon stabilitesi ilk gün seviyesine döner. Çankaya’daki otel, restoran ve plaza projelerinde bu protokol, HVAC yükünü azaltır, gürültüyü düşürür ve enerji verimini optimize eder. Yanlış basınç veya agresif kimyasal, üretici garantisini iptal eder; uzman bakım ise yatırımınızı korur. Kurumsal mekanlarda düzenli bakım, marka prestijini ve müşteri konforunu sürdürülebilir kılar. Mevsimsel denetimler ile mekanik yorgunluk erken tespit edilir, acil servis maliyetleri %60’a kadar düşer.</p>", snippet: "Çankaya projelerinde kurumsal bakım.", faqs: [{q: "Neden bakım?", a: "Motor ömrü için."}] },
  { slug: "antalya-konyalti-rolling-roof", title: "Antalya Konyaaltı’da Rolling Roof Temizliği", metaTitle: "Konyaaltı Rolling Roof Temizliği", metaDescription: "Tuz ve güneş hasarını önleme.", category: "Rolling Roof", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_BioClimatic_RollingRoof_1_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "Tuzlu nem ve UV etkilerine karşı restorasyon.", keywords: ["Konyaaltı", "Rolling Roof"], districts: ["Konyaaltı"], content: "<h2>Konyaaltı Protokolü</h2><p>Konyaaltı’nın tuzlu nem iklimi ve yoğun güneş ışınımları, alüminyum profil ve mekanik raylarda hızlandırılmış yorulma oluşturur. Yüzey hazırlık aşamasında HEPA kuru süpürme ile kum ve tuz kristalleri kaynağında uzaklaştırılır.</p><h3>Uygulama</h3><p>140°C, 3 bar kontrollü buhar uygulaması, alüminyum anotlama tabakasına zarar vermeden organik kir filmini çözer. Dr. Schnell onaylı pH 7.0 nötr neutralizer, tuz kalıntısını izole ederken EPDM contaları sertleştirmez. Ray temizliği, tekerlek senkronizasyonu ve motor tork ayarı ±3% toleransla kalibre edilir.</p>", snippet: "Tuz hasarını durdurun.", faqs: [{q: "Korozyon önlenir mi?", a: "Evet, nötr nötralizasyon ile."}] },
  { slug: "antalya-lara-zip-perde", title: "Antalya Lara’da Zip Perde Temizliği", metaTitle: "Lara Zip Perde Temizliği", metaDescription: "pH dengeli kumaş bakımı.", category: "Zip Perde", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_ZipScreen_ZipPerde_1_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "Kumaş gerginliği ve renk canlılığı için bakım.", keywords: ["Lara", "Zip Perde"], districts: ["Lara"], content: "<h2>Lara Bakımı</h2><p>Klasik yıkama kumaşı bozar, pH nötr temizlik ise korur. HEPA filtreli kuru toz alma ile UV birikimi ve statik partiküller yüzeyden çekilir.</p><h3>Uygulama</h3><p>110°C, 2 bar sıcak buhar, kumaş elyafına zarar vermeden kir tabakasını yumuşatır. Avrupa üretici onaylı antistatik ajan, statik elektriği nötralize ederken su itici özellikleri restore eder.</p>", snippet: "Zip perde ömrünü uzatın.", faqs: [{q: "Renk solar mı?", a: "Düzenli bakımla solmaz."}] },
  { slug: "ankara-etimesgut-wintent", title: "Ankara Etimesgut’ta Wintent Menteşe Bakımı", metaTitle: "Etimesgut Wintent Bakımı", metaDescription: "Rüzgar dayanımı ve menteşe kalibrasyonu.", category: "Wintent", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_BioClimatic_RollingRoof_2_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "Menteşe ve rüzgar kilitleri.", keywords: ["Etimesgut", "Wintent"], districts: ["Etimesgut"], content: "<h2>Etimesgut</h2><p>Menteşe yağlama ile sessiz çalışma. HEPA kuru toz alma ile menteşe yuvaları temizlenir.</p><h3>Uygulama</h3><p>125°C, 2.5 bar yüzey uyumlu buhar ile paslanmaz çelik ve alüminyum boya tabakasına zarar vermeden oksidasyonu giderir.</p>", snippet: "Rüzgara karşı tam dayanım.", faqs: [{q: "Fırtına hasarı?", a: "Kilit bakımı ile önlenir."}] },
  { slug: "ankara-yenimahalle-insaat-restorasyon", title: "Yenimahalle İnşaat Sonrası Restorasyon", metaTitle: "Yenimahalle Restorasyon", metaDescription: "İnşaat tozlarından arındırma.", category: "Bakım", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_CamTavan_1_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "Sıfır kalıntı ile teslimat.", keywords: ["Yenimahalle", "Tadilat"], districts: ["Yenimahalle"], content: "<h2>İnşaat Sonrası</h2><p>Yeni biten projeleriniz için özel temizlik çözümleri. HEPA kuru vakum ile 0.3µm altı partiküller uzaklaştırılır.</p><h3>Uygulama</h3><p>130°C, 2.5 bar kontrollü buhar, inşaat kalıntısını çözer. pH 6.9-7.1 nötr temizleyici kullanılır.</p>", snippet: "Sıfır hata ile teslimat.", faqs: [{q: "Zarar görür mü?", a: "HEPA toz alma ile korunur."}] },
  { slug: "antalya-alanya-cam-tavan", title: "Antalya Alanya’da Cam Tavan Bakımı", metaTitle: "Alanya Cam Tavan", metaDescription: "Hidrofobik leke giderme.", category: "Cam Tavan", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_BioClimatic_RollingRoof_3_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "Şeffaflığı koruyan hydrophobic kaplama.", keywords: ["Alanya", "Cam Tavan"], districts: ["Alanya"], content: "<h2>Alanya Bakımı</h2><p>Camlar lekesiz olmalı. Hydrophobic koruma ile leke sıfır.</p><h3>Uygulama</h3><p>115°C, 2 bar buhar ile temperli cam korunur. Nano hydrophobic ajan uygulanır.</p>", snippet: "Cam şeffaflığını koruyun.", faqs: [{q: "Leke tutar mı?", a: "Nano kaplama ile tutmaz."}] },
  { slug: "ankara-kecioren-gunes-paneli", title: "Ankara Keçiören’de Güneş Paneli Bakımı", metaTitle: "Keçiören Güneş Paneli", metaDescription: "Panel verimlilik bakımı.", category: "Diğer", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_GunesPaneli_2_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "İyonize su temizliği ile verim artışı.", keywords: ["Keçiören", "Panel"], districts: ["Keçiören"], content: "<h2>Panel Verimi</h2><p>Panel temizliği ile verimi artırın. HEPA kuru vakum ile kaba kum arındırılır.</p><h3>Uygulama</h3><p>110°C/1.5 bar buhar, fotovoltaik hücreyi korur.</p>", snippet: "Maksimum enerji verimi.", faqs: [{q: "Verim artar mı?", a: "Düzenli bakımla evet."}] },
  { slug: "antalya-muratpasa-tente", title: "Antalya Muratpaşa Tente Bakımı", metaTitle: "Muratpaşa Tente", metaDescription: "Kumaş gergi ve mekanik ayar.", category: "Tente", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_ZipScreen_ZipPerde_5_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "Kumaş ve ray senkronizasyonu.", keywords: ["Muratpaşa", "Tente"], districts: ["Muratpaşa"], content: "<h2>Muratpaşa</h2><p>Doğru gergi, uzun kumaş ömrü. pH 6.7 nötr kumaş bakımı uygulanır.</p><h3>Uygulama</h3><p>115°C, 2 bar buhar ile elyaf korunur.</p>", snippet: "Tente konforunu koruyun.", faqs: [{q: "Kumaş sızdırır mı?", a: "Su itici restore edilirse hayır."}] },
  { slug: "antalya-kas-kepenk", title: "Antalya Kaş Panjur ve Kepenk", metaTitle: "Kaş Kepenk Bakım", metaDescription: "Otomasyon ve tork ayarı.", category: "Kepenk", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_BioClimatic_4_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "Motor sessizliği ve korozyon önleme.", keywords: ["Kaş", "Kepenk"], districts: ["Kaş"], content: "<h2>Kaş</h2><p>Sessiz ve hızlı çalışın. HEPA toz alma ile motor muhafazası arındırılır.</p><h3>Uygulama</h3><p>130°C, 2.8 bar buhar, lamel yapısını korur.</p>", snippet: "Otomasyon stabilitesi.", faqs: [{q: "Sessiz çalışır mı?", a: "Sürtünme giderme ile evet."}] },
  { slug: "ankara-sogutozu-bioclimatic", title: "Ankara Söğütözü BioClimatic", metaTitle: "Söğütözü BioClimatic", metaDescription: "İklim uyumlu bakım.", category: "BioClimatic", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_BioClimatic_RollingRoof_4_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "HVAC optimize eden bakım.", keywords: ["Söğütözü", "BioClimatic"], districts: ["Söğütözü"], content: "<h2>Söğütözü</h2><p>Enerji tasarrufu sağlayın. Sensör ve motor bakımı yapılır.</p><h3>Uygulama</h3><p>120°C buhar ile elektronik aksam izole edilir.</p>", snippet: "Konforu optimize edin.", faqs: [{q: "HVAC yükü?", a: "Bakım ile düşer."}] },
  { slug: "kurumsal-zincir-bakim", title: "Kurumsal Zincir İşletmeler", metaTitle: "Kurumsal Bakım", metaDescription: "Marka standardı periyodik bakım.", category: "Kurumsal", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_ZipScreen_ZipPerde_7_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "Şube bazlı dijital raporlama.", keywords: ["Kurumsal"], districts: ["Genel"], content: "<h2>Kurumsal Bakım</h2><p>Standardize edin. Şube bazlı dijital raporlama ile marka imajını koruyun.</p>", snippet: "Marka bütünlüğü.", faqs: [{q: "Neden önemli?", a: "Müşteri güveni için."}] },
  { slug: "dis-mekan-guvenlik", title: "Dış Mekan Sistem Güvenliği", metaTitle: "Sistem Güvenliği", metaDescription: "Otomasyon güvenlik testi.", category: "Güvenlik", date: "20 Mayıs 2026", author: "PergoClean", image: "/assets/Blog/2_part/Blog_ZipScreen_ZipPerde_9_(ANKAmall_Armada_Cepa_Kentpark_Panora_Arcadium_Gordion_Acity_ForumAnkara_NataVega_Antares_365AVM_Taurus_OneTower_Metromall_Podium_Atlantis_NextLevel_Vega.webp", excerpt: "Güvenlik standartları.", keywords: ["Güvenlik"], districts: ["Genel"], content: "<h2>Güvenlik</h2><p>Sisteminizi test edin. Periyodik güvenlik kontrolleri.</p><h3>Uygulama</h3><p>Sensör, motor ve kilit mekanizması testleri.</p>", snippet: "Güvenli dış alanlar.", faqs: [{q: "Güvenli mi?", a: "Periyodik test ile."}] }
];